Offering brazier
MinerArcana/Astral pull request #57
Opened 2020-03-12 03:39 UTC by Alan19

- Make Psychic Inventory consist of 3 inventories (Regular, Astral, Inner Realm)
- More advancements
- Insert Keys of Enlightenment into Inner Realm inventory (Make sure you have space)
- Physical Body now pulls from capability
- Dim screen when Astral Travel starts (similar to bed)
  - Known bug: Effect occurs when logging in while Astral Travel is active
- Use `/burn` to insert items into a player's Inner Realm inventory

2020-03-12 19:27 UTC, SkySom requested changes

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
I'd move this into it's own Object so you can jsut pass in a single object, instead of recreating the anonomous class each time.

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/api/psychicinventory/PsychicInventory.java
> +    private HashMap<UUID, PsychicInventoryInstance> playerInventoriesMap = new HashMap<>();
Generally your Variable type should be the interface you're coding to, in this case Map<> = new HashMap<>()

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/api/psychicinventory/PsychicInventory.java
> +            psychicInventoryInstance.deserialize(nbt.getCompound(PSYCHIC_INVENTORIES).getCompound(s));
Seems not a great use of streams if you're gonna have to get the object multiple times.

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/blocks/OfferingBrazier.java
> +        if (!playerEntity.isSneaking() && entity instanceof OfferingBrazierTile) {
Why are you checking instance of this many times? Should check once and the handle the other pieces inside that if

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +    private LazyOptional<ItemStackHandler> getInventory() {
.... wut. No. Gods no.

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +        return getInventory().orElse(new ItemStackHandler(32));
orElseGet(() -> new ItemStackHandler(32), else you're creating that handler whether or not you use it.

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntityRenderer.java
> +        if (!entity.getGameProfile().isPresent()) {
```
entity.getGameProfile()
  .map(this::getSkin)
  .orElseGet(() -> new ResourceLocation())
```

2020-03-12 19:27 UTC, SkySom commented on src/main/java/com/alan199921/astral/util/UtilityFunctions.java
> +    public static ItemStack insertIntoAnySlot(IItemHandler itemHandler, ItemStack itemStack) {
See ItemHandlerHelper

2020-03-12 19:38 UTC, Alan19 commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
Should be resolved with 

https://github.com/MinerArcana/Astral/pull/57/commits/e68aa0617a5343fbaa1ddee428528b459eb5bc64

2020-03-12 19:38 UTC, SkySom commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
Nope, as you missed my entire point.

2020-03-12 20:02 UTC, Alan19 commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
Is this good?
https://github.com/MinerArcana/Astral/compare/e68aa0617a53...6dd612581149#diff-44a503853674df3a66dcf54eaa4616d9R72-R75

2020-03-12 20:03 UTC, SkySom commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
Much better, but now you see what I meant by saving code.

2020-03-12 20:03 UTC, Alan19 commented on src/main/java/com/alan199921/astral/Astral.java
> +                public INBT writeNBT(Capability<IPsychicInventory> capability, IPsychicInventory instance, Direction side) {
Yes. Thanks a lot!

2020-03-12 20:07 UTC, Alan19 commented on src/main/java/com/alan199921/astral/api/psychicinventory/PsychicInventory.java
> +            psychicInventoryInstance.deserialize(nbt.getCompound(PSYCHIC_INVENTORIES).getCompound(s));
Can you elaborate? Also, would a forEach loop be better?

2020-03-12 20:11 UTC, SkySom commented on src/main/java/com/alan199921/astral/api/psychicinventory/PsychicInventory.java
> +            psychicInventoryInstance.deserialize(nbt.getCompound(PSYCHIC_INVENTORIES).getCompound(s));
Probably? Just not calling nbt.getCompound for the same thing over and over again :D

2020-03-12 20:14 UTC, Alan19 commented on src/main/java/com/alan199921/astral/api/psychicinventory/PsychicInventory.java
> +    private HashMap<UUID, PsychicInventoryInstance> playerInventoriesMap = new HashMap<>();
This should be good
https://github.com/MinerArcana/Astral/commit/bd177cd78e4120e5156d7ce00aafc3871d25636a

2020-03-12 20:15 UTC, Alan19 commented on src/main/java/com/alan199921/astral/blocks/OfferingBrazier.java
> +        if (!playerEntity.isSneaking() && entity instanceof OfferingBrazierTile) {
That was a good catch. Thanks!
https://github.com/MinerArcana/Astral/commit/9b4b283c7a8a7ca0fd113af20c44291feb4a1430#diff-88e032c890ad64fafaab28a11b06753fR26-R30

2020-03-12 20:21 UTC, Alan19 commented on src/main/java/com/alan199921/astral/util/UtilityFunctions.java
> +    public static ItemStack insertIntoAnySlot(IItemHandler itemHandler, ItemStack itemStack) {
That's pretty handy.
https://github.com/MinerArcana/Astral/commit/50d0931178668970ed9cdfbc129311aad8735f63

2020-03-12 20:24 UTC, Alan19 commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +        return getInventory().orElse(new ItemStackHandler(32));
So the object in the parameter for orElse gets created even if it's not necessary?

2020-03-12 20:28 UTC, SkySom commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +        return getInventory().orElse(new ItemStackHandler(32));
yes, if you're using orElse, it just takes whatever is there into the function, thus it's a fully functional object

2020-03-12 23:26 UTC, Alan19 commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +        return getInventory().orElse(new ItemStackHandler(32));
I've switched to orElseGet for everything

2020-03-14 03:11 UTC, Alan19 commented on src/main/java/com/alan199921/astral/entities/PhysicalBodyEntity.java
> +    private LazyOptional<ItemStackHandler> getInventory() {
Got rid of the main inventory

2020-03-14 03:12 UTC, merged